### ISSUE TITLE
self._engine_proxy.wait_job crash

### ISSUE THREAD

**Issue by JinpengLI** [populse/soma-workflow#12]
La demande #8394 a été soumise par Souedet, Nicolas.
Defect #8394: Error while updating job status
Auteur: Souedet, Nicolas
Statut: New
Priorité: Normal
Assigné à:
Catégorie:
Version cible: soma-4.4
Resolution:
The following error occured after a long process run (3 hours and 40 minutes), but it seems quite complicated to reproduce.

EngineError
processes.py (2537) in _processExecution: 
Helper.wait_workflow(wid, controller)
client.py (1044) in wait_workflow: 
wf_ctrl.wait_job(job_ids)
client.py (587) in wait_job: 
self._engine_proxy.wait_job(job_ids, timeout)
engine.py (981) in wait_job: 
"The process updating its status failed." %(jid))

**Comment by denisri** [comment]
Seems outdated.
