### ISSUE TITLE
Installation on a distant computer

### ISSUE THREAD

**Issue by duboism** [populse/soma-workflow#14]
The current process for installation on a distant computer (e.g. a cluster) is very invasive (modification of `.bashrc`, `PATH`, `LD_LIBRARY_PATH` and `PYTHONPATH` variables, installation of code in `.soma-workflow`) and specific to our cluster (the path are hardcoded to match those on `gabriel`).

Some of those modifications are made because the cluster environment is a bit peculiar. For instance the default python version is 2.4. Version 2.7 is installed (in `/i2bm/brainvisa/CentOS-5.3-x86_64/python-2.7.3/`). As soma workflow needs 2.7 it adds it to the path. A side effect is that some the PBS tools are unable to work (because they are made for python2.4).

Specifically 2 case are to be distinguished:
1.  client launching process on the cluster: this happens when the client launches the database and engine servers; this is usually done trough SSH (by executing a command of the form `python -m ...`)
2. running workflow: in order for the workflow to execute it has to find some components (DRMAA, PBS, soma-workflow)

Another burden is that he code is copied to a hidden directory which make hard to modify or to use different versions.

Several actions could be taken to try to improve the situation:
- list what is needed in the environment for each case
- allow the user to configure how things are launched (for instance on `gabriel` python 2.7 can be launched with `python2.7`) and to modify the environment (we have to be careful here for security reasons)
- do not modify configuration files

**Comment by denisri** [comment]
Probably outdated.
