### ISSUE TITLE
It does not work on Python 3.4

### ISSUE THREAD

**Issue by alexsavio** [populse/soma-workflow#20]
Hi,

Do you have any plans regarding this? I would love to help.

Cheers

**Comment by denisri** [comment]
Hi,
None of our sotfware has been ported to python 3 so far. We will have to do it sooner or later, and help would be welcome. But we have to plan how to do so: we will need to maintain compatibility with python 2 until all our sorftware is completely ported to python 3, and this will be a huge and long work.
So we have to decide whether we try to maintain a single set of sources, using six for instance, or setup a different branch for python 3.
Denis

**Comment by denisri** [comment]
Porting to python3 (>= 3.5) is done now in soma-workflow 3.
